### PR TITLE
Update installer.ini

### PR DESCRIPTION
**Pull request by mohamedsharaf**
fix install url to version 9

### CODE REVIEW

**Comment by tvollstaedt** [comment]
Thanks for the effort, but just changing the URL is not enough to provide the newest version of PhpStorm. I just updated the repository to download 9.0.2.

**Comment by mohamedsharaf** [comment]
can u give me some guides on what need to be done and i will update the repository

**Comment by mohamedsharaf** [comment]
@tvollstaedt

**Comment by tvollstaedt** [comment]
@mohamedsharaf I have already updated the files to download the latest version. The downloaded file name and MD5 hash were also needed to be changed. You may look at the last commits to see the updates.

**Pull request closed without merging**
